version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend-app
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
      - '/home/project/data:/app'
    ports:
      - '443:3000'  # can edit
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - API_URL=${API_URL}
    ports:
      - "443:3000"
    volumes:
      - '/home/project/data:/app'
      - '/home/project/data:/code/app'
    env_file:
      - .env
