version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - API_URL=${API_URL}
    ports:
      - "443:3000"
    volumes:
      - '/home/project/data:/app'
      - '/home/project/data:/code/app'
    env_file:
      - .env
