version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend-app
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - API_URL=${BACKEND_URL}
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - '/home/project/data:/app'
      - '/home/project/data:/code/app'
    env_file:
      - .env
